=== erv96/FULLXML-David-Toledo-Carrasco-/books.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="book"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element maxOccurs="unbounded" ref="author"/>
                <xs:element ref="year"/>
                <xs:element ref="price"/>
                <xs:element ref="precio"/>
                <xs:element ref="priceS"/>
            </xs:sequence>
            <xs:attribute name="category" use="required" type="xs:NCName"/>
            <xs:attribute name="cover" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="title">
        <xs:complexType mixed="true">
            <xs:attribute name="lang" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="author" type="xs:string"/>
    <xs:element name="year" type="xs:string"/>
    <xs:element name="price" type="xs:string"/>
    <xs:element name="precio">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:decimal">
                    <xs:attribute name="moneda" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="priceS" type="xs:string"/>
</xs:schema>

=== erv96/FULLXML-David-Toledo-Carrasco-/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl"?>
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/xampp/htdocs/CENEC%202021%20-%201%C2%BA%20DAW/Lenguaje%20de%20Marcas/2%C2%BA%20Trimestre/EJERCICIO%20XML/books.xsd">
<book category="cooking">
  <title lang="en">OBRA:Everyday Italian</title>
  <author>Giada De Laurentiis</author>
  <year>Año: 2005</year>
  <price>Precio: </price>
  <precio moneda="€"> 29.99</precio>
  <priceS> euros </priceS>
</book>

<book category="children">
  <title lang="en">OBRA:Harry Potter</title>
  <author>J K. Rowling</author>
  <year>Año: 2005</year>
  <price>Precio: </price>
  <precio moneda="€"> 29.99</precio>
  <priceS> euros </priceS>
</book>

<book category="web">
  <title lang="en">OBRA:XQuery Kick Start</title>
  <author>James McGovern</author>
  <author>Per Bothner</author>
  <author>Kurt Cagle</author>
  <author>James Linn</author>
  <author>Vaidyanathan Nagarajan</author>
  <year>Año: 2003</year>
  <price>Precio: </price>
  <precio moneda="€"> 49.99</precio>
  <priceS> euros </priceS>
</book>

<book category="web" cover="paperback">
  <title lang="en">OBRA:Learning XML</title>
  <author>Erik T. Ray</author>
  <year>Año: 2003</year>
  <price>Precio: </price>
  <precio moneda="€"> 39.95</precio>
  <priceS> euros </priceS>
</book>

</bookstore>
